from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from src.core.database import get_db
from src.core.rbac import require_role, Role

from src.models.audit_logs import AuditLog
from src.api.schemas.audit_logs import AuditLogResponse


router = APIRouter()


# ============================================================
# GET ALL AUDIT LOGS
# ONLY SYSTEM ADMINISTRATOR
# ============================================================

@router.get(
    "",
    response_model=list[AuditLogResponse],
    dependencies=[Depends(require_role(Role.SYSTEM_ADMIN))]
)
def get_audit_logs(
    db: Session = Depends(get_db)
):
    """
    Get all audit logs.

    Audit logs are automatically generated by the system.
    Only System Administrators can view them.
    """

    logs = (
        db.query(AuditLog)
        .order_by(
            AuditLog.created_at.desc(),
            AuditLog.log_id.desc()
        )
        .all()
    )

    return logs


# ============================================================
# GET AUDIT LOG BY ID
# ONLY SYSTEM ADMINISTRATOR
# ============================================================

@router.get(
    "/{log_id}",
    response_model=AuditLogResponse,
    dependencies=[Depends(require_role(Role.SYSTEM_ADMIN))]
)
def get_audit_log(
    log_id: int,
    db: Session = Depends(get_db)
):
    """
    Get a specific audit log by ID.
    """

    audit_log = (
        db.query(AuditLog)
        .filter(
            AuditLog.log_id == log_id
        )
        .first()
    )

    if not audit_log:

        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Audit log not found"
        )

    return audit_log